DATASPINE_MODEL_NAME=CCFD \
DATASPINE_MODEL_TAG=cpu \
DATASPINE_MODEL_TYPE=keras \
DATASPINE_MODEL_RUNTIME=python \
DATASPINE_MODEL_CHIP=chip \
DATASPINE_INPUT_PATH=../input \
DATASPINE_OUTPUT_PATH=../output \
  python dataspine_predict.py
