DATASPINE_MODEL_NAME=ccfd \
DATASPINE_MODEL_TAG=a \
DATASPINE_MODEL_TYPE=keras \
DATASPINE_MODEL_RUNTIME=python \
DATASPINE_MODEL_CHIP=cpu \
DATASPINE_INPUT_PATH= \
DATASPINE_OUTPUT_PATH= \
  python dataspine_train.py